# Generated by Django 2.1.7 on 2019-06-04 00:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type_id', models.SmallIntegerField(choices=[(1, '后端开发'), (2, '前端开发'), (3, '数据结构&算法'), (4, '人工智能&大数据'), (5, '网络&操作系统'), (6, '数据库'), (7, '其他')], default=1, verbose_name='商品种类')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=200, verbose_name='商品简介')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('score', models.DecimalField(db_index=True, decimal_places=1, max_digits=3, verbose_name='豆瓣评分')),
                ('stock', models.IntegerField(default=10, verbose_name='商品库存')),
                ('sales', models.IntegerField(default=0, verbose_name='商品销量')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='商品详情')),
                ('image', models.ImageField(upload_to='books', verbose_name='商品图片')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='商品状态')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
    ]
